# Generated by Django 5.1.4 on 2024-12-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_dierctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='director',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
